const menu = [
  { 
    id: 1,
    title: "empanadas",
    category: "Tickets",
    price: 200.0,
    img: "./images/item-1.jpeg",
    desc: `An empanada is a type of baked or fried turnover consisting of pastry and filling, common in Spanish.`,
  },
  {
    id: 2,
    title: "brusquettas",
    category: "Tickets",
    price: 600.0,
    img: "./images/item-2.jpeg",
    desc: `Country bread, cream cheese, candied tomatoes (with 2 sauces, smoked eggplant, sweet locoto).`,
  },
  {
    id: 3,
    title: "Pumpkin Cream Soup",
    category: "Main",
    price: 1000.0,
    img: "./images/item-3.jpeg",
    desc: `Vegetables from the ravine, pumpkin, caramelized sweet potato and slices of parmesan.`,
  },
  {
    id: 4,
    title: "Cream Of Corn Soup",
    category: "Main",
    price: 1100.0,
    img: "./images/item-4.jpeg",
    desc: `Vegetables from the ravine, ground corn and jerky.`,
  },
  {
    id: 5,
    title: "Mix Of Greens With Vegetables",
    category: "Main",
    price: 1200.0,
    img: "./images/item-5.jpeg",
    desc: `Green leaves, candied tomatoes and baked vegetables with carrot dip`,
  },
  {
    id: 6,
    title: "Arugula And Quinoa Salad",
    category: "Main",
    price: 1300.0,
    img: "./images/item-6.jpeg",
    desc: `Arugula, quinoa, red onion, carrot, with yogurt dip.`,
  },
  {
    id: 7,
    title: "Quinoa Casserole",
    category: "Main",
    price: 1700.0,
    img: "./images/item-7.jpeg",
    desc: `Quinoa casserole, vegetables and glazed carrots.`,
  },
  {
    id: 8,
    title: "Ribbon Noodles",
    category: "Main",
    price: 1100.0,
    img: "./images/item-8.jpeg",
    desc: `Additional: mushroom sauce $600, tuco $550, cream $450 and mixed sauce $500.`,
  },
  {
    id: 9,
    title: "Lamb Stew",
    category: "Main",
    price: 2300.0,
    img: "./images/item-9.jpeg",
    desc: `Lamb stew with black beer, gratin potatoes and a touch of fine herbs.`,
  },
  {
    id: 10,
    title: "Stuffed Arepas",
    category: "Main",
    price: 1900.0,
    img: "./images/item-10.jpeg",
    desc: `On sunflower seed cream (Chicken with a variety of peppers / Wok vegetables and eggplant hummus).`,
  },
  {
    id: 11,
    title: "Ribbon Noodles (Kids Menu)",
    category: "Main",
    price: 800.0,
    img: "./images/item-11.jpeg",
    desc: `Tape noodles with fillet sauce, cream, olive and cheese.`,
  },
  {
    id: 12,
    title: "Pizza (Kids Menu)",
    category: "Main",
    price: 900.0,
    img: "./images/item-12.jpeg",
    desc: `Pizzettes with fresh tomato sauce and mozarella.`,
  },
  {
    id: 13,
    title: "Roasted Peaches",
    category: "Deserts",
    price: 700.0,
    img: "./images/item-13.jpeg",
    desc: `Roasted peaches on anchi cream base common in Spanish, other Southern European, Latin American`,
  },
  {
    id: 14,
    title: "Homemade Flan",
    category: "Deserts",
    price: 700.0,
    img: "./images/item-14.jpeg",
    desc: `Homemade flan with caramel, optional dulce de leche and/or cream.`,
  },
  {
    id: 15,
    title: "Brownie With Ice Cream",
    category: "Deserts",
    price: 850.0,
    img: "./images/item-15.jpeg",
    desc: `Brownie with American cream ice cream and red fruit coulis.`,
  },
  {
    id: 16,
    title: "Cheese With Sweet Cayote",
    category: "Deserts",
    price: 750.0,
    img: "./images/item-16.jpeg",
    desc: `Quesillo with sweet cayote, walnut and cane honey.`,
  },
];
export default menu;
